languages:
  HTML: true
  CSS: true
  JavaScript: true
engines:
  fixme:
    enabled: true
  exclude_fingerprints:
    - bad6800d6d16f9bbd62e163feda7273d
    - 5a72b127d9458342ef9693ce07256c09
  csslint:
    enabled: true
ratings:
  paths: []
exclude_paths: []